In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('wine_3.xlsx')

In [4]:
df.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash    Magnesium  \
0  Type1    14.23        1.71  2.43                 15.6        127   
1  Type1    13.20        1.78  2.14                 11.2        100   
2  Type1    13.16        2.36  2.67                 18.6        101   
3  Type1    14.37        1.95  2.50                 16.8        113   
4  Type1    13.24        2.59  2.87                 21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [5]:
x=df.drop('Class',axis=1)

In [6]:
y=df['Class']

In [7]:
import numpy as np

In [8]:
np.unique(y)

array(['Tpye3', 'Type1', 'Type2'], dtype=object)

In [9]:
df.describe()

Alcohol  Malic acid         Ash  Alcalinity of ash     Magnesium  \
count  178.000000  178.000000  178.000000           178.000000  178.000000   
mean    13.000618    2.336348    2.366517            19.494944   99.741573   
std      0.811827    1.117146    0.274344             3.339564   14.282484   
min     11.030000    0.740000    1.360000            10.600000   70.000000   
25%     12.362500    1.602500    2.210000            17.200000   88.000000   
50%     13.050000    1.865000    2.360000            19.500000   98.000000   
75%     13.677500    3.082500    2.557500            21.500000  107.000000   
max     14.830000    5.800000    3.230000            30.000000  162.000000   

       Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       Color intensity         Hue  OD280/OD315 of diluted wines      Proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
x = scaler.fit_transform(x)

In [13]:
pd.DataFrame(x).describe()

0             1             2             3             4   \
count  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02   
mean  -8.382808e-16 -1.197544e-16 -8.370333e-16 -3.991813e-17 -3.991813e-17   
std    1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00   
min   -2.434235e+00 -1.432983e+00 -3.679162e+00 -2.671018e+00 -2.088255e+00   
25%   -7.882448e-01 -6.587486e-01 -5.721225e-01 -6.891372e-01 -8.244151e-01   
50%    6.099988e-02 -4.231120e-01 -2.382132e-02  1.518295e-03 -1.222817e-01   
75%    8.361286e-01  6.697929e-01  6.981085e-01  6.020883e-01  5.096384e-01   
max    2.259772e+00  3.109192e+00  3.156325e+00  3.154511e+00  4.371372e+00   

               5             6             7             8             9   \
count  178.000000  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02   
mean     0.000000 -3.991813e-16  3.592632e-16 -1.197544e-16  2.494883e-17   
std      1.002821  1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00   
min     -2.107246 -1.695971e+00 -1.868234e+00 -2.069034e+00 -1.634288e+00   
25%     -0.885468 -8.275393e-01 -7.401412e-01 -5.972835e-01 -7.951025e-01   
50%      0.095960  1.061497e-01 -1.760948e-01 -6.289785e-02 -1.592246e-01   
75%      0.808997  8.490851e-01  6.095413e-01  6.291754e-01  4.939560e-01   
max      2.539515  3.062832e+00  2.402403e+00  3.485073e+00  3.435432e+00   

                 10            11            12  
count  1.780000e+02  1.780000e+02  1.780000e+02  
mean   1.995907e-16  3.193450e-16 -1.596725e-16  
std    1.002821e+00  1.002821e+00  1.002821e+00  
min   -2.094732e+00 -1.895054e+00 -1.493188e+00  
25%   -7.675624e-01 -9.522483e-01 -7.846378e-01  
50%    3.312687e-02  2.377348e-01 -2.337204e-01  
75%    7.131644e-01  7.885875e-01  7.582494e-01  
max    3.301694e+00  1.960915e+00  2.971473e+00

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.3)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
logmodel = LogisticRegression()

In [18]:
logmodel.fit(xtrain, ytrain)

LogisticRegression()

In [19]:
ypred = logmodel.predict(xtest)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(confusion_matrix(ytest, ypred))

[[14  0  0]
 [ 0 18  0]
 [ 4  0 18]]


In [22]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

       Tpye3       0.78      1.00      0.88        14
       Type1       1.00      1.00      1.00        18
       Type2       1.00      0.82      0.90        22

    accuracy                           0.93        54
   macro avg       0.93      0.94      0.92        54
weighted avg       0.94      0.93      0.93        54

